Backend/src/FinalPhase/Controllers/PurchasesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Backend.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Collections.Generic;
using CryptoHelper;
using YouFlyModels;
using Microsoft.AspNetCore.Authorization;

namespace Backend.Controllers
{
    public class PurchasesController : Controller
    {
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Index()
        {
            string myURL = "https://yfapig3.azurewebsites.net/api/purchaseapi/";
            var client = new HttpClient();
            var response = await client.GetAsync(myURL);
            if (response.IsSuccessStatusCode)
            {
                var items = JsonConvert.DeserializeObject<List<Purchase>>(
                    await response.Content.ReadAsStringAsync());
                return View(items);
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult Error()
        {
            return View();
        }

    }
}

Backend/src/FinalPhase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/style.css" />
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>

<center>
    <div class="container">
        <header>
            <hr style="height: 1px;color: #27aae1;background: #27aae1;" />
        </header>
    </div>
</center>

<body style="background-image:url('http://i66.tinypic.com/2m81pjk.jpg')">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <div class="pull-right">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("ADMIN"))
                    {
                        <form method="post" asp-controller="Home" asp-action="Logout">
                            <a asp-area="" asp-controller="Routes" asp-action="Index" class="navbar-brand">Routes</a>
                            <a asp-area="" asp-controller="Users" asp-action="Index" class="navbar-brand">Users</a>
                            <a asp-area="" asp-controller="Purchases" asp-action="Index" class="navbar-brand">Purchases</a>
                            <input class="btn btn-primary" type="submit" value="Logout" />
                        </form>


                    }
                    else
                    {
                        <a asp-area="" asp-controller="Home" asp-action="Login" class="btn btn-primary">Log In</a>
                    }
                </ul>
            </div>
        </div>

    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br />
    <div class="panel panel-default">
        <div class="panel-footer">
            <div class="container narrow row-fluid">
                <p style="color:#000000"><img src="http://i68.tinypic.com/2gw6jpy.jpg" style="width:50px;height:50px;" img-responsive"> 2017  ||  You Fly, We Design  ||  Admin Panel, All Rights Reserved </p>
                <hr style="height: 3px;color: #000000;background: #808080;" />
            </div>
        </div>
    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/assets/js/scripts.js"></script>
        <script src="~/assets/js/jquery.backstretch.js"></script>
        <script src="~/assets/js/jquery-1.11.1.js"></script>
        <script src="~/assets/js/jquery-1.11.1.min.js"></script>
        <script src="~/assets/js/jquery.backstretch.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>


    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>